---
title: "Efficient R Programming \\ Chapter 3"
author: "Michael Flanagin  \\ flanna@uw.edu"
date: "7/31/2018"
classoption: portrait
header-includes:
  - \usepackage[table]{xcolor}
  - \usepackage{booktabs}
  - \usepackage{caption}
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    number_sections: yes
  html_document:
    fig_caption: yes
    force_captions: yes
    highlight: pygments
    number_sections: yes
    theme: cerulean
---
  
```{r libraries, eval = TRUE, cache = TRUE, echo = TRUE, message = FALSE}
library("microbenchmark")
library("compiler")
library("memoise")
library("pryr")
library("profvis")
```


# Format model parameters
```{r 0-test-list-initialization, eval = TRUE, cache = TRUE, echo = TRUE}
library("microbenchmark")
f0 <- function( n ){
  result_list <- vector( mode = "list", length = n )
  for( i in seq_along( LETTERS[1:n] )){
    result_list[[ i ]] <- LETTERS[ i ];
  }
}
f1 <- function( n ){
  result_list <- list();
  for( i in seq_along( LETTERS[1:n] )){
    result_list[[ i ]] <- LETTERS[ i ];
  }
}
f2 <- function( n ){
  result_list <- lapply( LETTERS[1:n], function( .letter ) return( .letter ) )
}
f3 <- function( n ){
  result_list <- list();
  result_list <- lapply( LETTERS[1:n], function( .letter ) return( .letter ) )
}
f4 <- function( n ){
  result_list <- vector( mode = "list", length = n );
  result_list <- lapply( LETTERS[1:n], function( .letter ) return( .letter ) )
}

microbenchmark(f0( n = 26 ), f1( n = 26 ), f2( n = 26 ), f3( n = 26 ), f4( n = 26 ))

# Conclusion:
#   > Initialize lists with vector( mode = "list", length = n )
#   > Use for() loop to populate list
#   ( Doesn't matter if list populated with lapply() )
```

```{r 1-eval-memory-used, eval = TRUE, cache = TRUE, echo = TRUE}
# Evaluate memory usage by R in the current session
pryr::mem_used()
#' TODO(michael): Read and review memory usage here
#' ref: http://adv-r.had.co.nz/memory.html
```

```{r 2-test-unlist-lapply-vs-sapply, eval = TRUE, cache = TRUE, echo = TRUE}
f0 <- function( n = 1e4 ){
  unlist(lapply( 1:n, function( .seed ){ set.seed( .seed ); rnorm(1) }))
}
f1 <- function( n = 1e4 ){
  sapply( 1:n, function( .seed ){ set.seed( .seed ); rnorm(1) })
}
microbenchmark( res0 <- f0(), res1 <- f1() )
identical( res0, res1 )
```


```{r 3-test-subset-vs-vector-of-logicals, eval = TRUE, cache = TRUE, echo = TRUE}
n <- 1e4;
set.seed( 1515 )
foo <- data.frame(X = rnorm( n ), Y = sample(c(TRUE, FALSE), size = n, replace = TRUE ));
  
f0 <- function( ){
  subset( foo, subset = foo$Y, select = "X" )
}
f1 <- function( ){
  #' [ using indexing ]
  foo$X[ foo$Y ]
}
f2 <- function( ){
  #' [ using indexing, matrix notation ]
  foo[ foo$Y, "X" ]
}
microbenchmark( res0 <- f0(), res1 <- f1(), res2 <- f2() )
# Unit: microseconds
#          expr     min       lq     mean   median       uq      max neval cld
#  res0 <- f0() 449.379 508.3530 589.1448 541.0665 574.0250 2765.687   100   b
#  res1 <- f1()  84.865  96.9575 129.4857 101.7675 109.0645 1906.749   100  a 
#  res2 <- f2() 103.123 109.6425 133.2046 112.7205 120.7095 1631.206   100  a 
identical( res0, res1 )
#' Conclusion:
#' [1] using subset() is slow as fuck.
```
